### ISSUE TITLE
Fail listing photo in capture club

### ISSUE THREAD

**Issue by Cryptoguy86** [numbersprotocol/community-support#85] opened 2022-02-14 07:55 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Capture App (please complete the following information):**

**Select label**
Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub

**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1203248717867306) by [Unito](https://www.unito.io)

**Comment by Cryptoguy86** [comment] 2022-02-14 07:55
I got same issue before, but I wasn't sure about.
The bug is, when you want to list a photo to capture club and you do pay for the listing fee and gas fee, the process will deduct the amount but without completing the listing in the capture club. You have to do the process again and another deduction to be able listing the photo again in capture club.

**Comment by Cryptoguy86** [comment] 2022-02-14 07:57
Device : IPhone 11 plus
Os : IOS 
Version:15.2.1
Capture app ver: 0.46.1

**Comment by tammyyang** [comment] 2022-02-17 08:46
@kennyhungQA are you able to verify this?

**Comment by kennyhungQA** [comment] 2022-02-17 10:49
About the first description, I can't reproduce it.
But I notice you need to wait 10-15 mins for listing your captures.

**Comment by Cryptoguy86** [comment] 2022-02-17 10:54
Yes, I understand that but the photos I listed it didn’t list till now, I
waited around one to two days and when it’s not listed I do it again and
again I pay the fees to list it again.
Now it happened to me 6 times

How I can help to provide more info to you ?!?

Best regards

**Comment by kennyhungQA** [comment] 2022-02-17 11:09
Please provide me your e-mail, I could check your order history. Thanks for your help. :)

**Comment by Cryptoguy86** [comment] 2022-02-17 11:11
Sure, here it is.

***@***.***

**Comment by Cryptoguy86** [comment] 2022-02-17 11:12
How I can provide you with my email ?

**Comment by Cryptoguy86** [comment] 2022-02-17 11:12
It's show ***

**Comment by kennyhungQA** [comment] 2022-02-18 03:09
HI, @Cryptoguy86  Thanks for your reporting, our team had got your email, we'll check more detail and follow up on this. :)

**Comment by kennyhungQA** [comment] 2024-03-26 08:28
CaptureClub is no longer supported. We welcome you to continue experiencing the seamless Web3 experience provided by Numbers Protocolo through [Capture Dashboard](https://dashboard.captureapp.xyz/). Close this issue.

**Closed by kennyhungQA** 2024-03-26 08:28 UTC
Labels: capture-app
