### ISSUE TITLE
Hasnain

### ISSUE THREAD

**Issue by Ahmadhasnain44** [numbersprotocol/community-support#363] opened 2024-02-20 10:21 UTC
**Describe the bug**

**To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

A clear and concise description of what you expected to happen.**Screenshots**

If applicable, add screenshots to help explain your problem.**Capture App (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Select label**

Based on the issue category, please select a label from General/Capture App/NFT Search Engine/CaptureClub**Additional context**

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1203248692432071/1206642673654471) by [Unito](https://www.unito.io)

**Comment by ethanwu155** [comment] 2024-02-22 07:17
@Ahmadhasnain44 thanks for taking the time to fill out an issue report. If you can provide more details about this issue such as what product (app, dashboard, etc.) that would be helpful to identifying the issue.

As many of our products have '...' it would be helpful if you can provide more information. Providing screenshots and error messages can also go along way to reproducing the issue you mentioned.

Looking forward to your response.

**Comment by bafu** [comment] 2024-03-15 17:00
Because there is no sufficient information, I will close this issue directly. Please feel free to reopen it if there is more input.

**Closed** 2024-03-15 17:00 UTC
