### ISSUE TITLE
Editing/Filters

### ISSUE THREAD

**Issue by Shipwrck86** [numbersprotocol/community-support#26] opened 2021-12-30 03:03 UTC
**Is your feature request related to a problem? Please describe.**
Upload a picture to the system that has image correction or even filters.

**Describe the your user story**
After uploading my picture I noticed I couldn’t make any adjustments to the photos. Without profession photo lighting and design the photos fall kind of flat. Using some filters or build in camera controls would make the NFT stand out. 

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**

**Select label**
Based on the issue category, please select a label General

**Additional context**

**Comment by KNctrl-alt** [comment] 2021-12-30 05:26
Hey @Shipwrck86 , this is a great one but unfortunately someone else already started this issue at #8. So, for reducing redundancy please click on `Close issue` and move the discussion there. You can upvote the original issuer and additionally add your comments under that discussion.
This project has always been about authenticity in digital media so adding filters and editing capabilities within the ecosystem has been a great topic of discussion/debate so please feel free to add your views there.

**Comment by bafu** [comment] 2022-01-11 09:35
Duplicate of #8

**Closed** 2022-01-11 09:40 UTC
